#!/usr/bin/env python

# -- Sphinx Options -----------------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_design",
    "myst_parser"
]

suppress_warnings = []

# Add any paths that contain templates here, relative to this directory.
templates_path = []

# General information about the project.
from datetime import date

project = "cramjam"
author = "Miles Granger"
year = date.today().year
copyright = f"{year} Miles Granger"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "_build",
    "target",
    "README.md",
]


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "pydata_sphinx_theme"

fontawesome_included = True

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "search_bar_text": "Search ...",
    "navbar_persistent": [],
    "secondary_sidebar_items": [],
    "footer_items": ["copyright"],
    "icon_links": [
        {"name": "GitHub", "url": "https://github.com/milesgranger/pyrus-cramjam", "icon": "fab fa-github"},
    ],
}

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# Setting the baseurl will add the canonical link to the <header> of our pages
html_baseurl = ""

# turn off switching between light and dark mode
html_context = {"default_mode": "light"}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = ""

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

html_css_files = []

html_js_files = []

github_pages = "cramjam"

# Panels config
panels_add_bootstrap_css = False

# redirects
rediraffe_redirects = {}
