name: CI-libcramjam

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-test:
    name: capi=${{ matrix.capi }}-codec=${{ matrix.codec || 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ !( startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags/') ) }}
      matrix:
        capi:
          - true
          - false
        codec:
          - zstd
          - blosc2
          - gzip
          - brotli
          - lz4
          - xz
          - deflate
          - bzip2
          - null  # Use all codecs

        # TODO: codecs not implemented in capi feature
        exclude:
          - capi: true
            codec: blosc2
          - capi: true
            codec: xz
          - capi: true
            codec: deflate
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        name: Rust Cache

      - name: Audit
        if: |
          !matrix.codec && matrix.capi
        run: cargo install cargo-audit && cargo audit

      - name: Test capi and single codec
        if: matrix.capi && matrix.codec
        run: cargo test -p libcramjam --no-default-features --features ${{ matrix.codec }} --features capi --lib

      - name: Test capi and all codecs
        if: matrix.capi && !matrix.codec
        run: cargo test -p libcramjam --features capi --lib

      - name: Test no capi and all codecs
        if: |
          !matrix.capi && !matrix.codec
        run: cargo test -p libcramjam --lib

      - name: Test no capi and single codec
        if: |
          !matrix.capi && matrix.codec
        run: cargo test -p libcramjam --lib --no-default-features --features ${{ matrix.codec }}
