name: MasterCI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: Python Dev Install
        run: pip install -r dev-requirements.txt

      - name: Build Wheels - Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          docker build . -t milesg/maturin:latest
          docker run --rm -v $(pwd):/io milesg/maturin:latest sh -c "source ~/.cargo/env && maturin build --release --out wheels"

      - name: Build Wheels - Non-Linux
        if: startsWith(matrix.os, 'windows') || startsWith(matrix.os, 'macos')
        run: |
          pip install maturin
          maturin build --release --out wheels

      - name: Install wheel
        run: pip install cramjam --no-index --find-links wheels

      - name: Test
        run: python -m pytest -v


